### ISSUE TITLE
GreenPass-Experiments

### ISSUE THREAD

**Issue by grildev** [jojo2234/Human-Method#1]
Hey, your repo "GreenPass-Experiments" was disabled, can you send me the repo in zip or rar format?
thanks a lot bro

**Comment by TakeOver66** [comment]
Ciao jojo, anche io tempo fa ho lavorato al DCC. Soltanto che l'ho sviluppato in C#
Peccato che il tuo repository sia stato chiuso, ho tratto molti spunti dal tuo codice! Purteoppo mi sono arenato anche io all private Key! Al momento riesco a genereare un certificato firmato, ma, non valido!! Potremmo comunque scambiarci alcune informazioni 😁 
https://ibb.co/pPNx0Q9

**Comment by jojo2234** [comment]
Sorry, this is not an issue. My previous project has been concluded. 
Thank you for your interest in the project.

Read carefully this project and tell me if you are able to generete a key pair because I encounter some errors, whoever is able to do that  I will appreciate if can make a pull request.

Thank you.

**Comment by grildev** [comment]
> 

Same, i have problems with the "signature" thing, jojo please, lets talk about your greenpass experiment!

**Comment by grildev** [comment]
@jojo2234

**Comment by grildev** [comment]
also please can you check your twitter

**Comment by grildev** [comment]
i think i know how to fix it!

**Comment by jojo2234** [comment]
Fix what? My previous project works and it's concluded. 

If you have a valid Italian Green Pass and the Italian Private Key you can make a custom valid Green Pass the same could happen if you have a German Green Pass and the German Private Key but if you have a valid Italian Green Pass and a valid German Private Key you must change the KID inside the customized Green Pass before sign it otherwise validators apps will detect it as not valid.

That'all, my previous project was working. Now in this project related with ECDSA I have a problem while generating a KeyPair because of an exception if you are able to fix it, just make a pull request and I will be happy to accept it.

Thank you.

**Comment by melottimarco** [comment]
@jojo2234 come faccio a contattarti in privato?
protonmail o telegram?
